name: latexmk
on: [push]
jobs:
  action-test:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run latexmk
        run: "latexmk --lualatex"
      - name: Archive documentation
        uses: actions/upload-artifact@v4
        with:
        name: Documentation
          path: "./*.pdf"
          retention-days: 3
        